[build]
  base = "fundeca-client"
  command = "npm ci && npm run build"
  publish = "dist/fundeca-client"

# SPA fallback for Angular router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
